COURT_WIDTH = 255
COURT_HEIGHT = 191
COURT_COLOR = 0
COURT_TICK_WIDTH = 3
COURT_TICK_HEIGHT = 5
COURT_TICK_COLOR = 7

PLAYER_WIDTH = 4
PLAYER_HEIGHT = 24
PLAYER_1_X = 15
PLAYER_2_X = COURT_WIDTH - 15 - PLAYER_WIDTH

PLAYER_SPEED = 3
PLAYER_COLOR = 11

BALL_WIDTH = 4
BALL_COLOR = 11

PRE_START_FRAME_DELAY = 60

# How many points needed to win
WIN_SCORE = 1
