COURT_WIDTH = 255
COURT_HEIGHT = 191
COURT_COLOR = 0
COURT_TICK_WIDTH = 1
COURT_TICK_HEIGHT = 2
COURT_TICK_COLOR = 7

PLAYER_WIDTH = 2
PLAYER_HEIGHT = 10
PLAYER_1_X = 10
PLAYER_2_X = COURT_WIDTH - 10 - PLAYER_WIDTH

PLAYER_SPEED = 2
PLAYER_COLOR = 11

BALL_WIDTH = 1
BALL_COLOR = 11

PRE_START_FRAME_DELAY = 60
